apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:KLxcmmV3sD2p4lT+h+/ot4yerE2Do9dAYTSnz0+WI5ljZIA6X6b5QnY3/hXmmkwYYDn9vHg+g0lrNk8VWaHer5Y=,iv:2wZZTKGL62BJJTzBgIzvukT15FFN91muDBpleIb3Umg=,tag:WFt2NB1jTa6Bd6fe/r7ygQ==,type:comment]
    #ENC[AES256_GCM,data:X53SGhwkPx4+jy+BOeYLKTv8i6IM1RberjO8C81VODKbBJWXMo8OA04YvUo=,iv:UbDmXpugZKhKo1H3RoyoxEf+VIn02Gw5Jr4r+S21Lm4=,tag:InvbNiwH62CZQIeQ9zqzKg==,type:comment]
    VIP: ENC[AES256_GCM,data:AJO7ug+O0kEJBBSg+g==,iv:rw8LN4jxz6HXSpq7a49issNJDbhqb6CFsQvNEyY8aRM=,tag:iD6VHjWxwXJkYSck5WT7dA==,type:str]
    #ENC[AES256_GCM,data:kohrOUpFzII7kPCrBjSfz5KzREL5OPJiLFXo,iv:LkuZc3crAEFixeZ44DoLHIkU3wIgiexr87q/+FcLNG0=,tag:VFjVcfhVTBPf/QA1o6yAsQ==,type:comment]
    #ENC[AES256_GCM,data:OvYrErGhkALVHuK9og8zp2cP2M1wqbHw2YLNp/ZTnlaAjZWQW/1sPgVBiGSOz9jDC7ar8vmIIxTA6O0Cx4rTt+QhZwSLE/l+Bj7yV6L5XjcW84XrybFU9gk=,iv:O13Hq1v9tv8YBjg0leVdL7nigN1Ai0MWoKeEHsJb14Y=,tag:1Jxn6yTOjrwpow/gVc1Juw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:Y8KHo97UhlRr3Z2SnA==,iv:COdpWfEkCHsBOVGqE9Oae2NqrRGi/ZU1bjTIu8W3uTc=,tag:Yd6dyET0Uzx+pKdChSSokA==,type:str]
    #ENC[AES256_GCM,data:YdP5SZ3qUaE3x/ENPESm3I+0P/O4OXU0mgIlhguPtiWWKA==,iv:ljLvXLCPTj4gJD/jxQTwuX+DGWj0juEbfvAjdJ6Nt8s=,tag:dunAjEr5iMq+OfVGUz+C0A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:jB1gFer5dIwhqxY=,iv:VYXnZadYtyN30o9uP2/ap3uL+vfSBi+GjrzPNAPTTxc=,tag:MNqWvOKWIDKu01iNyoAIfw==,type:str]
    #ENC[AES256_GCM,data:Tg7ydj8V3UtZh1If0Fz9+H6UrnktJ2MgllZ7cg81WK2E4wQKT3gjaQuvqw75fKQ=,iv:3VWzAy1bVWgUgbyvdqBy4gsyjQ5BRHXSFeERDFjpNM8=,tag:CoYaWavpHePE25nSpq6twA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:w49vPYtQm1AjMmcN5bQiAA+7ShjDL7c2EjfR,iv:B+KdCfaD8Hbvw8Gu9il5JemRD1Tl0/uoce0xmjTFkeo=,tag:oaTagaFXnigF04DerRv8mQ==,type:str]
    #ENC[AES256_GCM,data:ZPUxhU2UpZZow/XRWV42ZTHQTXhbNCblltIoDejXXyjVJ3jD/xvF0CbDT+JeWLuDL9T9775dU9gNHDluLJFiwJqHrAC9vKS8dJskXldqeiXGFQ==,iv:orzSrF7MKANlc5YWn++x2dSQDuh5yzfo0MrJAhFgBQ4=,tag:j9QCy0Npeh0OfqmA+JGEdQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:c/VYXY5BIvRYz8CVBA==,iv:VrSbFcsG8KMeuSi3mCLxr19mrunyvNres3uEE9Sp8gk=,tag:QrimiVEE2XlHVV0+XMGhnw==,type:str]
    #ENC[AES256_GCM,data:+BOwHJ/OsxiIy0HcEyu/dVVVLASn2l8qzRbmD4rzLoDt,iv:dTJarVJhZhHES5ZNw6QtgTW2RCjDidh3bqSqtk+Hf48=,tag:qc0MGWUy4NAy9Kx8YqKH9g==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:CPzFwqqLH56J2PMi1g==,iv:ZpWQAIF3lMf08kZBc1T3dILQYf8i2WnY5o0sR695b+g=,tag:SqZGD9KSDOlwi6nNwnRDrg==,type:str]
    #ENC[AES256_GCM,data:q4hICKyrZsOsmffKThxyqPFADJlQ/1PXzDwk9VUlccRnLq73piA2FWLQ6S+0DPwkk2eUQqrGTKg4DSTRydxexbBUJH7V1O73Feyy++HICvo=,iv:7B3fTJoYq2vTnvmq/kXKEhj4K4fJv2keHlkOBPlCytA=,tag:LqPR2+O86nLBdNbE7A/jrQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:aGwePiMxj6BK7sdC2w==,iv:llqYWgQNOru1uuCC8i6iuSBApwkN1o4+LMccYloLxLo=,tag:628Z9BnLroof0gbImpc0BA==,type:str]
    #ENC[AES256_GCM,data:1gb0kHu5Dx1cKVQP2hUsL3U12MxhJ4IWQPqVcPd5XiT6r4euSYPEtxD6z+5NgFVYaQ9INR4qLvjauzEl0a6Tf2ejWE/VodDk4wEXE2zaArqU5MV31xAh,iv:K5cYFc+O82GyS5ZGJlHVWRDW9itMZY/zqvHPmGsl2Sk=,tag:6CqQsVacrK8X/vVnMxewfw==,type:comment]
    #ENC[AES256_GCM,data:Uaum1gLlSc4tVE6U8ENhAo7fHq12olFm392jAOKVL1kB2oFMl3lAB2GlHnp+5VwtTkKNMZyWP7MUEM5IYI+nDfZ1bxAMQzKS+g0mWJmhZU+l5KOaEUMJG7zA4PyN++YhHg5DAY1Oq7tgTweLY/+rfwKV43/REg6E+4vqgw==,iv:oMXBpPRyOGBaDosVzh1B2T9zuoM2B/NpiCU/zdeE7qY=,tag:Sl1oB09ypQnOYrA3/U50eA==,type:comment]
    #ENC[AES256_GCM,data:QW+eLKGp2RLtCamuNwVOVNc3h3otTXYU5H66mmSMIQbhR4mcs2+GJ3dt+yCK/1cEX6HdODffgnAWu5DMvedEbjJBl3ENv2x8bkQXhuiMDM8=,iv:xCFl1DP5hXk63AMpxOOXTlrsTAtgkDAQGjxA0FG8tuA=,tag:K3oC24GbvssV3bVsXYy6Ig==,type:comment]
    #ENC[AES256_GCM,data:Zz3mCawnTmW1JneGhZRfHy+WmReuc0LwOBJWA44z2PBFqs269OzLfDp83cXmAzmfWe49txZK,iv:C+AiuY2rJd8/sLslWBcz0/1GL7VpF9pesVMbwtOjnXc=,tag:8JM62GB3pWWVHZiWc80fyw==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:qwQ2a6wVsQbeBA9e,iv:P9XX7DJZPoYKQ6JSziL8vP2N1kYi8y6p7cqa1bzzhuk=,tag:cauNCXkTp4r8riGvynq8gA==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:xn24k2a+SyacBoNMh3nDu8c=,iv:VkleqgeFKOmrdEAzlxaBTVvJ7y8J7Mx//GNSAEWPKNk=,tag:73qqRJM5+hzEMptiSPnJpQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:wfqA5C/D4lxyf7g7uDyWgEbhDR01cwcVvPh//RE5uhl8+hrfbhUBjw==,iv:X9QzEQk+0i9eDl0L7WoF5fEfaZQPOHLqkoFVatCrvLk=,tag:xcjiDDZPXJsUfOYS099/KA==,type:str]
    #ENC[AES256_GCM,data:vDKeR9ZRCk8qdZ7a5uNah+G/wXm4YGSjEZBAcujz6bGKm9Z9ESX2mPOJTAY0MF/XiUAhUK+d5eQ=,iv:oLpk3q1/Qeqb8DzwdwKF+kkW9R+ski0Idhcnz7OghEI=,tag:HD7AyipEE1AxZVEbrf1rHg==,type:comment]
    #ENC[AES256_GCM,data:+pCUsGHS7NtIxcu6B0oiRL5hYFCA55SzEQ==,iv:+uepz75w/oXYM9JXNapuihigquR0/ACwIGpAHmmYPnI=,tag:PRbOau7OJiHz0+HMugaSSg==,type:comment]
    #ENC[AES256_GCM,data:8860DPofQd4fzews17IgKj2K3KloN65S1E8ovAjrzeMZkXUcvhkvJw7kPb7EoyFistJMdCPq+NHNZYlmSl+pzjCPe3B72wHbX6CagEY=,iv:7HwmntJv6mQ1K1YPyxa+YdlCcVTx3ZNAdwRHKux62n4=,tag:bg+mjJIPi5ZLB01JmaOJ0g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:wMDoL4guvW6KEcXEw3FSKKJZR/oiSjvA5GspjDpo/MDYwyvS/jeJejsRJCvwjd4=,iv:J59kkP/gfonM3nluVYRYxuUVYVfqM3+YUETF3p/hRQA=,tag:RdvDMgTxbuzYUDRLIsy7SA==,type:str]
    #ENC[AES256_GCM,data:uZtGLO4AvtJ5qY8yKmbIWLDp3jD8CMCDKTf1KqGa0J8GvdKcsab2H508LcLcbpXq+z53SSqpjJtOFK2ct/1OMKAXgKI5OSs=,iv:4Ewe5QDAlgJLOXCs3XwEP2kgz7WiaFnrxMcK6ngzXIk=,tag:V0j1mm2c88zQfzEyhRwC1Q==,type:comment]
    #ENC[AES256_GCM,data:c6/dXvcn8eXZf+WvTRT/NbaUjNGcZuNGklEF/aPEL58wgbs9v63XMNDpaTHWOiRBCjVSeBr8,iv:bL2q2kCamEX4cSsbiZLEZk1W6gGPeDIH1tFgf+bj6to=,tag:4xlDvHUj76gs61EcLvtmdA==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:/IMD8BudLw==,iv:yp5K3FX+InWwDyyxhHCO7x48PpTMaswyJ4fnSEZnEcM=,tag:n2Uk2HmCYPQkJb5V95HzQw==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:PGbR5hN/NcB0tMbUIoQyld/UpEQ=,iv:6pPNUARAIP4BUB+/vInE+dwpE7t/3XUhds923a7Bwak=,tag:rT8Gb0gHBJrsAW0GKVhCLA==,type:str]
    #ENC[AES256_GCM,data:ksXtafOE1rFF64HV3GI=,iv:jAON7IJojR172OlBmEhGn5JB54G0rO8Ym3PfxvGrSkQ=,tag:7wUVPqJbGy6YK9+foPedLA==,type:comment]
    PODNET: ENC[AES256_GCM,data:vnFE1c4lJTVCf5RtfA==,iv:W6itmE2vjz/F+6ua8sftFPjjc00/cDVCxXYDNjEF/Xg=,tag:Tf2jZIBoYkiliLE2GmaEvQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:aGdtntA0/aWFYvjTVg==,iv:yo9BU1cMQMKcrIveB11wM/TYZfqGm9W3Fbu6wkLGWos=,tag:JlZF4Hv1znhx8OlOKL5IKA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:XEXT0A==,iv:BPd5WQdBl6rBQmRpCJIJ5RaEiqfs5UelWV+aUtsH/as=,tag:6DQfuG/xKX9rkpWl91jUgA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163zrrrens6pfh3vtrurxveqqssdra9lgdgzuhvnd8kmx7ptv7cmqmkpwzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYS9ORFdhN2ozWGlHWWNL
            Kzk1cmFDQ1BmZ1lKOTZRYkErbHJoZi9YSzJJCjZpVVlzbzM1VVdXdFB6Zm91YnNa
            dGI1M24wbHdLUnpjWUkxQkdVY1QvdzQKLS0tIC9iWE5ZYmI3NWt4R1lxb2gwM012
            S0hWWnFQK2w0RkMxUmRFVlVJeHBnaHcKSgZsiTlfDW5+zlN8IhZrZ4O0Gugggad2
            Iks10iNFaUI2685s9Xf2tYr6vDqCmA5GsfLcjVgY+q5A+cdK4lwALQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T20:35:02Z"
    mac: ENC[AES256_GCM,data:jjhfm4zzJoQcVeS2m2bQRWy7x3j4aCWNy3x04u5OcKWi9j0qSjhEgFtB/9/Ed0fRz9InKr/ADul+S4Qg1PjWJqpc1YXD/RELBh1+5RPNpBl6g2wnfv3Gk08ZKqfTojiiCaQNOnNfmIQwKePZG19RWQKHy3uERo01v5t9XN1DBVI=,iv:hVzzjR5z5gudUz4ExLiXMo7WsIcvFYn6Xo9xdV58878=,tag:NEpgSSd9y6mdPobSwgWJ0Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
