apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ctw1Gr0+ktOj909oFEpSCHQ/quejIhmU0kx0a/G7puDduo0/XTsXh2+wH9gP42IYNJg7ZDGnPuCIUnoXWwxP2Ab/WYi/N7g40wuVEG5FJnwNJ87S8eIc9XIgyuLbyvJgOquSZL8A743zFOf2ftcOkD4budbYV8EM7LH6QIrsgvF9RFlTOW7lWtLDVOXTZ6ZmlKpqEEtL6x+QjA+LZx/trB5xAEnRqp79L44ZH6mKxkQyCeZTat4LU2AqxzqdYOKfgFasGEio5SQuVrztWhcbn2rbsJ/w1HdHGCsmvAE6T1wi85iTcmiFMKr+Xmh4MFxja3kqyQYXNrryr3StmME2NMyCrFh/joEgeEtKBByrAhwxKm0XfN6PudjSL6Xy2weT,iv:Kwl8+4JEwGz78bnbX5OuUNVrdLB5ksZSolePSk53RPU=,tag:pJlk12s83lHaOfizMHI4JA==,type:str]
    identity.pub: ENC[AES256_GCM,data:RvJr46crh/EFP+D5sPcchjvGL61x4fDj4rD7TEvop0eJV8YDf5w4SqaDA49cjpPBbXORgmHg1Su+DnX9TwXks40FNhXrh5pS+0r4JlKLLthQ+L701dEs4btZJ6SG0bx0o9sY6JwUDGUbQkDFv28cth2JxOebs7xf1v5RsUyfMV3e68e9mdEQH1vwMSlHF20Kg4R5gvvzjnpC6ShWvcX70jT0wBFUgEp4eHxJU8a7tl+TqbqEhRFHNFzBNnpCQpgoT9J2JF6N++GJ8DxPQQ==,iv:m5oftblBAUAq1R5HO0UV05Nt9wOSs2RrFMGEr72BT/c=,tag:hHI0DIfs8Bt3nwDhtp7N/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:shgKzIfplJ7bvXtq9AgNzV6JkfUqBvs8GRl6A7TGireize4bDscVEXzBwt2yMa7cjj6OowWONpp7dmzDhmgyx8lTw1GO4L00MQ6Yf7oPN88phzmfE7rrM2gLw8f10dHTCFFIXwnBPrlLzUPTBMuTt1mCMYUsXzws7Pr354z3bbRggjrjstYg5aS/lh9Lm/uDRGPdtA9I/qwMooVhW06S7YgEVvP5K5sgMC+A,iv:AJQHiSLy7XE5q/RFmqLjsJ6Z4a4pnVNlNESTk6rt5rY=,tag:Pe1tWebA9CkQKmRWhE+q7g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163zrrrens6pfh3vtrurxveqqssdra9lgdgzuhvnd8kmx7ptv7cmqmkpwzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb3gzQkVlbE1OYUZOdGZy
            QXphR29TWUM2VklpYUU4eVJxbUg3Ulcwb1hrCmVzalhLaWZIUGt3Z3pzb1pVT2Rt
            Mm5pamoyVVdrVVU5NHowNE5jd3NISHMKLS0tIFRTdlR1OHMwdU5XYU5NQmJ2S3FP
            NGtUT2ZnVVBmNjB0OG05RDFqZVYyNU0KOt5/RDUXaAiX4AhpUGGRRu1LxThcW3FW
            Guhma/piPXyRYU4WkXDXRkiaFvIL4AslreE+PI6rbt8oiHNF8NJtlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T06:41:49Z"
    mac: ENC[AES256_GCM,data:0pkrIKnD0Y7o6vIdlHSu2SIbmBP5vT9OEN8GV5Y5sod9Jor2njG3WPKR0lWHH4u993DJa3rSEbc6cPzlyjAzr/A2imGyHRf8P5lGAA30l2LoI4yxK1DjOQKxVkxEqgNg+WqsLcK5Drjo88haoYc/arAOKJ+xTwf7OaGTsX226LY=,iv:MQPVEBiS+wU2ZRv+WKkKvVPxfnnezL7jIaVuEp1etyQ=,tag:yDwaddyC/LWjWB4iL/O9gQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
