apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HjhDGD4VmKE1Uj4mngFbWS+UiOtV5uhIoWrv/oqV9i0mOUmNt5I6NyBHPIj+iVZncbtTgrTM/oD5OBw7R9E0q4vAVcAZKBkPUX6UObFz7E5W1esowdpviiN2HKkGTCIUkhcRmolY+Gjeu0BMC2zsGCJbYMqd6SqzM8L7Vri4sGCxB57l4WSonPAJmQM6SUsuTS70/Rsbd1GPcjOMdzwZCJVd6fP3V9oI9mw05xNvCbxzy3lTgBaS3Ev66lyStRCTNwcAKWp3j874c5QGeETs1HHnD9FJVGtTiiEaiTbgcKZp2WkPXsf3VTcCU/aY+UtOCAtGXcJoCfyCCHCeHjuc25+qK5bDz+dDtLjpkQRnFW9hLHuHUhVtJlI8Uyu2JiEB,iv:Dojk/j9eOC6We/TmsalLwdeSjDUOdxv94ZCk7hVHDs0=,tag:CqCXFjY/RlcFKbkgQY6WsA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Tx7Qcwq2/63eP6fOsKrVIKUf0YmIJnfou+xzjwHK9J/tosVm5zrQC4ZvlQ3YZq3+OxjwPKvqu9Xxq3fKUFOi4PoGEXMYfFW5yztY7ZcaKKHahBdETJVcOQsSEwcbUT7r2GBYfSA458Y+V7voQgPh/K0WS2xh3gBOYp2REh9IYM1D5CjSVAo3qkO894+CQucSIaEzXkFO0VxEWhlOtbnHAtbMqukNNuOTP4LpIzQ42LXPp6Uomg15AFAAlfEsREN3Pr3fYdy/iMsNQAaz1g==,iv:7RyEj0Nx5eSUCuF88AvMS1h9oxaI4Z/XL6U67B26+bg=,tag:0hiivvDxfdG6qqlaVUxm4g==,type:str]
    known_hosts: ENC[AES256_GCM,data:xC5x3ch/lMdJTXm2pbaF913LcfT4VuTGTUpDdCrzWKIf0SyrIfP4f/WNJ9hERYpfPHSeGL/pZWI4W0ZV5f+tCXU1Gz+/yibYEkxWcBTR0U82ild51R7GyC7n59Yy9uV6c5r/aXNSZx6vwBhRkjZYcnRlmP+jFzwGZ+4ATCoL/elFcDlgqPenVi2MICyJV1NapPDE9B5JH36KJCG1oJHkkkElYOM6wu5DXCKZ,iv:S7Wsd/lOwwNFSiPtwFdORGTitOygBsZuJI+mPTQud7c=,tag:VOXwuumPUo8DIJG1k+VYpQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163zrrrens6pfh3vtrurxveqqssdra9lgdgzuhvnd8kmx7ptv7cmqmkpwzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RVowK0tnd0IrWWVhMFdZ
            RXIxZUNpb1RJQjhPMXdIdlFORkkrZWVSZno4Cm1adzl0L2N4NCtXRzA4S1lodXlQ
            NWVJQXQ3NEoxMUh5RTRwd2FDanIwNE0KLS0tIEJIaU5SR3RuTytsdkhTL1dOSGpU
            ODJtOGtKRkJVNVNTUzBOZU54SjQ2bEUKadL+gu6+jKO2Z1d7/x12m2ALzsmjP2Nd
            w4aFg8Ltijjf/OW7CqCdtOxwfkxymy8T3EcNXQY2ziSFxe85yErNGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T21:22:26Z"
    mac: ENC[AES256_GCM,data:0fNHru1iMnGtZycKhvJbFMBDeUXAz3h7hpT2m9WLy69gsY6gkcQcVbS8cwyHO0sjSUV7St1pLnZoGAYXse2BJOxvPwhNoV+W6hkOaMQeBpCETqa/O2zg15e63pn+DjpliU6OqIT3L86Os7juNTdlNFjObYrVrdPBjQh4jeJm0xU=,iv:2JbpJTYZQD7pbqRCmuxwwcv2odfjs/CsD4+Vtz/zRag=,tag:xd8IAzLGF76G16ftKWq09g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
