apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qr9z5jj/ln2pV5YBvTNz2zS+/WdOvwMg9OgC5dtEsfGjws6Fiado7ogiT2Fa0/LdEV5a/dugTobc/rLWg327tkslvioUjHV0gTmO1sVNtt/vnZZfQtBu65wunveRUYf37z6nDCVOfPSif3zI2urpJmDHu9BrcGH4bluMnM8dpT33+HmaM1t27gxI+qYI/8bxHApQyszhGyem5dJ4Y5uhAl/sZ3+yf1e15XrV8xiQmXci4F1WPjR47s3WpO2VSeJbhTaSpkqGeTw1g6+qmwUun/euJHedA1kf9dCuhuF/utX8ac7azB5HxKWBnVGSMo1r5/58bSpCFQmomkDXyrd+Rx1AWodtv+GPAI5XW891Y+yyoC/vXoAphX/jcj0CDeX/,iv:Sx0XOdVAbGhFAT5q5eDbk+33n2mclqSqfS2DoQDlMRg=,tag:p0F5TAkjUMXJJFxVrlWiBQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:77gKAYDwdiqfLScjsZ2Vm+GX3ilmuEn2hNZPJl4z8gI7DPuGl8YOicKUJwzsn046BNNHnucIMyQCRRUAvw9PuQARdPsw7cp7SD5FTRCM+OzVPhQXfveauZhons+xWx3pQosYJbHDRbppbGjdvJXmNvdzmhY5Av+uasMNInSN7KVRwNtCFn/JcNj4rgdOHEcJqQxXfk+b0qZGBOMPFqXUp3sQAqKAflPP87twxNm9kpnJ+tjIAzLgpxY0dppOMXLvBkUIOAVtyQkGBzOCnw==,iv:c1z9XVOG36V27dmd2IXhhf9qyzAi5H0E3DszuVMKeI8=,tag:xzlvMvhaT76pU2Uf0lMmaw==,type:str]
    known_hosts: ENC[AES256_GCM,data:qWhXr8qo6laAKCgIhP3E9b/K2RQiQcOHdXH8O3yvP+S8RIkEKrJPnfn/titw1K3gMpM6MMm+UicUjiiLQySiDqAoDGvD0Al27NeWO35tsxRocfWDJEwfsijksvdjyC670sZcus4Y/USLrpu42GwJO7pY/QxiGx10NhKpVzgK5Mm3Amm+tQSyTbksfJy/kNWf86wV03xbgujq8HhSJYphaF5xbFpRYSuPVmyi,iv:oXxknHURexCxWjRU9Ofz6L50un+0jYg6aRPgdHZyMPI=,tag:92S2aJeep1cLS9A0Qd2z6g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163zrrrens6pfh3vtrurxveqqssdra9lgdgzuhvnd8kmx7ptv7cmqmkpwzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VHlpQ1FhQWdqVnl0aHYv
            NE9jWlJPOUw4MWNoWC9oaWdhRm51WFJvUTJjCm4xVjQybGY0UVdNK2pWZnNWTHZr
            YVBpNjhUVjZHN3c4ay9wRFcyR3k5OVUKLS0tIGxRUGZCTW84b3NibjhrTzFpL0xu
            WUVHd1RJMHlpWjFOb0dFRCt4dnd3TWMKRtK1hVynGHFj9hTCMO7EzU5/TcEZWfyf
            P+nSqoUitxDg3qtY29xavQRmEmRq/5PwbHS/Yorl6A/duR9MAoGv3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T20:35:02Z"
    mac: ENC[AES256_GCM,data:8cS3WimxsaJ5lR2A3rY/WWozXo+xU7uqpColIaKVbDVfiBI3cIm/BxgcxdCnqPKbuDhjiQpFOIcQdyV97CS8tUwFYilVoCzPOQY15D0qxv7ynP4TbW+4uJ0OXzkAv6LNOM1NZFH3wtWnP4j58mJnkLO1pnBvTkkFBQXdMP3XVjQ=,iv:ShYCtdagaP/uSewR5NCtHgeL5tb9VxLn69xKICBhCOY=,tag:klbYkTSkEBtoKddtkZ943A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
